require_relative './likes'

DISCUSSION_VARIANTS = [
  "{\"blocks\":[{\"key\":\"erakd\",\"text\":\"Soufflé biscuit caramels bear claw gingerbread. Chupa chups sweet wafer biscuit candy canes jelly dragée tart pie. Bear claw gummi bears cheesecake topping chocolate powder gummi bears cheesecake jujubes. Liquorice powder chocolate icing. Muffin chocolate bar biscuit cake dessert. Halvah chocolate sweet jelly gummi bears. Marzipan jelly-o candy candy cotton candy. Jelly beans topping tiramisu cupcake lollipop liquorice biscuit chocolate bar. 🤓\",\"type\":\"unstyled\",\"depth\":0,\"inlineStyleRanges\":[{\"offset\":0,\"length\":447,\"style\":\"fontfamily-Arial\"},{\"offset\":367,\"length\":77,\"style\":\"UNDERLINE\"}],\"entityRanges\":[],\"data\":{\"text-align\":\"left\"}},{\"key\":\"e2122\",\"text\":\"Marzipan tootsie roll sugar plum caramels gummies carrot cake chocolate macaroon.\",\"type\":\"unordered-list-item\",\"depth\":0,\"inlineStyleRanges\":[{\"offset\":0,\"length\":81,\"style\":\"fontfamily-Arial\"}],\"entityRanges\":[],\"data\":{\"text-align\":\"left\"}},{\"key\":\"cdfb0\",\"text\":\"Pie caramels brownie powder gummies biscuit muffin.\",\"type\":\"unordered-list-item\",\"depth\":0,\"inlineStyleRanges\":[{\"offset\":0,\"length\":51,\"style\":\"fontfamily-Arial\"},{\"offset\":0,\"length\":51,\"style\":\"BOLD\"}],\"entityRanges\":[],\"data\":{}},{\"key\":\"7hhpv\",\"text\":\"Liquorice powder ice cream biscuit cotton candy jelly croissant jelly.\",\"type\":\"unordered-list-item\",\"depth\":0,\"inlineStyleRanges\":[{\"offset\":0,\"length\":70,\"style\":\"fontfamily-Arial\"}],\"entityRanges\":[],\"data\":{}},{\"key\":\"bcvdt\",\"text\":\"\",\"type\":\"unstyled\",\"depth\":0,\"inlineStyleRanges\":[],\"entityRanges\":[],\"data\":{}},{\"key\":\"e99bi\",\"text\":\"Bear claw biscuit candy pastry chocolate bar. Candy gummies liquorice apple pie biscuit. Chocolate bar gingerbread apple pie toffee apple pie jelly-o carrot cake oat cake chupa chups. Liquorice gummi bears ice cream danish.\",\"type\":\"unstyled\",\"depth\":0,\"inlineStyleRanges\":[{\"offset\":0,\"length\":223,\"style\":\"fontfamily-Arial\"}],\"entityRanges\":[],\"data\":{}},{\"key\":\"4gsaa\",\"text\":\"Marzipan muffin jelly beans toffee muffin liquorice macaroon. Chocolate donut jelly biscuit chocolate bar gingerbread jelly beans. Cookie marshmallow marshmallow tootsie roll cotton candy wafer. Tiramisu tart tart soufflé sweet jelly beans muffin wafer sesame snaps. Ice cream pudding chupa chups macaroon. Topping dragée sugar plum ice cream muffin ice cream cookie jujubes soufflé. Chocolate cake marzipan chocolate bar icing chocolate bar pudding. Wafer topping powder soufflé chocolate.\",\"type\":\"unstyled\",\"depth\":0,\"inlineStyleRanges\":[{\"offset\":0,\"length\":490,\"style\":\"fontfamily-Arial\"}],\"entityRanges\":[],\"data\":{\"text-align\":\"left\"}}],\"entityMap\":{}}",
  "{\"blocks\":[{\"key\":\"f2ihu\",\"text\":\"Veggies es bonus vobis, proinde vos postulo essum magis kohlrabi welsh onion daikon amaranth tatsoi tomatillo melon azuki bean garlic.\",\"type\":\"unstyled\",\"depth\":0,\"inlineStyleRanges\":[{\"offset\":0,\"length\":134,\"style\":\"fontfamily-Arial\"}],\"entityRanges\":[],\"data\":{\"text-align\":\"left\"}},{\"key\":\"aorpr\",\"text\":\"Gumbo beet greens corn soko endive gumbo gourd. Parsley shallot courgette tatsoi pea sprouts fava bean collard greens dandelion okra wakame tomato. Dandelion cucumber earthnut pea peanut soko zucchini.\",\"type\":\"unstyled\",\"depth\":0,\"inlineStyleRanges\":[{\"offset\":0,\"length\":201,\"style\":\"fontfamily-Arial\"},{\"offset\":0,\"length\":201,\"style\":\"ITALIC\"}],\"entityRanges\":[],\"data\":{\"text-align\":\"left\"}},{\"key\":\"7hngi\",\"text\":\"Turnip greens yarrow ricebean rutabaga endive cauliflower sea lettuce kohlrabi amaranth water spinach avocado daikon napa cabbage asparagus winter purslane kale. Celery potato scallion desert raisin horseradish spinach carrot soko. Lotus root water spinach fennel kombu maize bamboo shoot green bean swiss chard seakale pumpkin onion chickpea gram corn pea. Brussels sprout coriander water chestnut gourd swiss chard wakame kohlrabi beetroot carrot watercress. Corn amaranth salsify bunya nuts nori azuki bean chickweed potato bell pepper artichoke.\",\"type\":\"code\",\"depth\":0,\"inlineStyleRanges\":[{\"offset\":0,\"length\":549,\"style\":\"fontfamily-Arial\"}],\"entityRanges\":[],\"data\":{\"text-align\":\"left\"}},{\"key\":\"7uu1h\",\"text\":\"Nori grape silver beet broccoli kombu beet greens fava bean potato quandong celery.\",\"type\":\"ordered-list-item\",\"depth\":0,\"inlineStyleRanges\":[{\"offset\":0,\"length\":83,\"style\":\"fontfamily-Arial\"}],\"entityRanges\":[],\"data\":{}},{\"key\":\"fub4\",\"text\":\"Bunya nuts black-eyed pea prairie turnip leek lentil turnip greens parsnip.\",\"type\":\"ordered-list-item\",\"depth\":0,\"inlineStyleRanges\":[{\"offset\":0,\"length\":75,\"style\":\"fontfamily-Arial\"}],\"entityRanges\":[],\"data\":{}},{\"key\":\"b376f\",\"text\":\"Sea lettuce lettuce water chestnut eggplant winter purslane fennel azuki bean earthnut pea sierra leone bologi leek soko chicory celtuce parsley jícama salsify.\",\"type\":\"ordered-list-item\",\"depth\":0,\"inlineStyleRanges\":[{\"offset\":0,\"length\":160,\"style\":\"fontfamily-Arial\"}],\"entityRanges\":[],\"data\":{}}],\"entityMap\":{}}",
]

def create_random_discussions!(options)
  puts 'Creating discussions...'

  all_users_ids = User.all.pluck(:id)

  options[:amount].times do |index|
    tag_list = Faker::Lorem.words(rand(options[:max_tags_per]))
                           .join(', ')

    discussion = Discussion.create!(
      title: "#{index}-#{Faker::Lorem.sentence(5, true, 5)}",
      description: DISCUSSION_VARIANTS.sample,
      author_id: all_users_ids.sample,
      tag_list: tag_list
    )

    likers_ids = all_users_ids.sample(rand(options[:max_likes_per]))
    add_likes_to(discussion, likers_ids)
  end
end
