AllCops:
  Include:
    - Rakefile
    - config.ru
    - lib/**/*.rake
    - app/**/*.rb
  Exclude:
    - db/schema.rb

Rails/HasAndBelongsToMany:
  Enabled: false

Rails/SkipsModelValidations:
  Enabled: false

Metrics/LineLength:
  Enabled: false

Style/Documentation:
  Enabled: false
